@Webshop_HostAddress = https://localhost:7081

GET {{Webshop_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{Webshop_HostAddress}}/weatherforecast

###

GET {{Webshop_HostAddress}}/api/user

###
